var map_info = [{ id: "AFG", name: "Afghanistan", info: [{name: "", work:"to be updated"}] },
{ id: "AGO", name: "Angola", info: [{name: "", work:"to be updated"}] },
{ id: "ALB", name: "Albania", info: [{name: "", work:"to be updated"}] },
{ id: "ARE", name: "United Arab Emirates", info: [{name: "Shamma bint Suhail Faris Mazrui", work:"Shamma bint Suhail Faris Mazrui is believed to be the youngest government minister in the world and her role is to create pathways for young people to have more engagement with government and within society."}] },
{ id: "ARG", name: "Argentina", info: [{name: "", work:"to be updated"}] },
{ id: "ARM", name: "Armenia", info: [{name: "", work:"to be updated"}] },
{ id: "ATA", name: "Antarctica", info: [{name: "", work:"to be updated"}] },
{ id: "ATF", name: "French Southern and Antarctic Lands", info: [{name: "", work:"to be updated"}] },
{ id: "AUS", name: "Australia", info: [{name: "", work:"to be updated"}] },
{ id: "AUT", name: "Austria", info: [{name: "", work:"to be updated"}] },
{ id: "AZE", name: "Azerbaijan", info: [{name: "", work:"to be updated"}] },
{ id: "BDI", name: "Burundi", info: [{name: "", work:"to be updated"}] },
{ id: "BEL", name: "Belgium", info: [{name: "", work:"to be updated"}] },
{ id: "BEN", name: "Benin", info: [{name: "", work:"to be updated"}] },
{ id: "BFA", name: "Burkina Faso", info: [{name: "", work:"to be updated"}] },
{ id: "BGD", name: "Bangladesh", info: [{name: "", work:"to be updated"}] },
{ id: "BGR", name: "Bulgaria", info: [{name: "", work:"to be updated"}] },
{ id: "BHS", name: "The Bahamas", info: [{name: "", work:"to be updated"}] },
{ id: "BIH", name: "Bosnia and Herzegovina", info: [{name: "Ilya Lozovsky", work:"Ilya Lozovsky is Managing Editor at OCCRP. Prior to joining the organization, he worked for Foreign Policy in Washington, where he edited and wrote for the magazine's Democracy Lab channel. Ilya has also worked as Program Officer for Eurasia at Freedom House, providing emergency support to human rights activists and organizations across that continent. "}] },
{ id: "BLR", name: "Belarus", info: [{name: "", work:"to be updated"}] },
{ id: "BLZ", name: "Belize", info: [{name: "", work:"to be updated"}] },
{ id: "BOL", name: "Bolivia", info: [{name: "", work:"to be updated"}] },
{ id: "BRA", name: "Brazil", info: [{name: "", work:"to be updated"}] },
{ id: "BRN", name: "Brunei", info: [{name: "", work:"to be updated"}] },
{ id: "BTN", name: "Bhutan", info: [{name: "", work:"to be updated"}] },
{ id: "BWA", name: "Botswana", info: [{name: "", work:"to be updated"}] },
{ id: "CAF", name: "Central African Republic", info: [{name: "", work:"to be updated"}] },
{ id: "CAN", name: "Canada", info: [{name: "", work:"to be updated"}] },
{ id: "CHE", name: "Switzerland", info: [{name: "", work:"to be updated"}] },
{ id: "CHL", name: "Chile", info: [{name: "", work:"to be updated"}] },
{ id: "CHN", name: "China", info: [{name: "", work:"to be updated"}] },
{ id: "CIV", name: "Ivory Coast", info: [{name: "", work:"to be updated"}] },
{ id: "CMR", name: "Cameroon", info: [{name: "", work:"to be updated"}] },
{ id: "COD", name: "Democratic Republic of the Congo", info: [{name: "", work:"to be updated"}] },
{ id: "COG", name: "Republic of the Congo", info: [{name: "", work:"to be updated"}] },
{ id: "COL", name: "Colombia", info: [{name: "", work:"to be updated"}] },
{ id: "CRI", name: "Costa Rica", info: [{name: "", work:"to be updated"}] },
{ id: "CUB", name: "Cuba", info: [{name: "", work:"to be updated"}] },
{ id: "-99", name: "Northern Cyprus", info: [{name: "", work:"to be updated"}] },
{ id: "CYP", name: "Cyprus", info: [{name: "", work:"to be updated"}] },
{ id: "CZE", name: "Czech Republic", info: [{name: "", work:"to be updated"}] },
{ id: "DEU", name: "Germany", info: [{name: "Luisa Neubauer", work:"Luisa Neubauer is a German activist in the field of climate change. "}] },
{ id: "DJI", name: "Djibouti", info: [{name: "", work:"to be updated"}] },
{ id: "DNK", name: "Denmark", info: [{name: "", work:"to be updated"}] },
{ id: "DOM", name: "Dominican Republic", info: [{name: "", work:"to be updated"}] },
{ id: "DZA", name: "Algeria", info: [{name: "", work:"to be updated"}] },
{ id: "ECU", name: "Ecuador", info: [{name: "", work:"to be updated"}] },
{ id: "EGY", name: "Egypt", info: [{name: "Amr Gharbeia", work:"Amr Gharbeia is interested in the juncture between technology, politics and the law. Over 12 years, he has helped communities and civil society use ICT for social change."}] },
{ id: "ERI", name: "Eritrea", info: [{name: "", work:"to be updated"}] },
{ id: "ESP", name: "Spain", info: [{name: "", work:"to be updated"}] },
{ id: "EST", name: "Estonia", info: [{name: "", work:"to be updated"}] },
{ id: "ETH", name: "Ethiopia", info: [{name: "", work:"to be updated"}] },
{ id: "FIN", name: "Finland", info: [{name: "", work:"to be updated"}] },
{ id: "FJI", name: "Fiji", info: [{name: "", work:"to be updated"}] },
{ id: "FLK", name: "Falkland Islands", info: [{name: "", work:"to be updated"}] },
{ id: "FRA", name: "France", info: [{name: "", work:"to be updated"}] },
{ id: "GAB", name: "Gabon", info: [{name: "", work:"to be updated"}] },
{ id: "GBR", name: "England", info: [{name: "", work:"to be updated"}] },
{ id: "GEO", name: "Georgia", info: [{name: "", work:"to be updated"}] },
{ id: "GHA", name: "Ghana", info: [{name: "", work:"to be updated"}] },
{ id: "GIN", name: "Guinea", info: [{name: "", work:"to be updated"}] },
{ id: "GMB", name: "Gambia", info: [{name: "", work:"to be updated"}] },
{ id: "GNB", name: "Guinea Bissau", info: [{name: "", work:"to be updated"}] },
{ id: "GNQ", name: "Equatorial Guinea", info: [{name: "", work:"to be updated"}] },
{ id: "GRC", name: "Greece", info: [{name: "", work:"to be updated"}] },
{ id: "GRL", name: "Greenland", info: [{name: "", work:"to be updated"}] },
{ id: "GTM", name: "Guatemala", info: [{name: "Helen Mack Chang", work:"Helen Mack Chang is a Guatemalan businesswoman and human rights activist."}] },
{ id: "GUY", name: "Guyana", info: [{name: "", work:"to be updated"}] },
{ id: "HND", name: "Honduras", info: [{name: "", work:"to be updated"}] },
{ id: "HRV", name: "Croatia", info: [{name: "", work:"to be updated"}] },
{ id: "HTI", name: "Haiti", info: [{name: "", work:"to be updated"}] },
{ id: "HUN", name: "Hungary", info: [{name: "", work:"to be updated"}] },
{ id: "IDN", name: "Indonesia", info: [{name: "EngageMedia", work:"EngageMedia is used by Malaysians to encourage young people to become citizen journalists."}] },
{ id: "IND", name: "India", info: [{name: "Mariya Salim", work:"Bharatiya Muslim Mahila Andolan (Indian Muslim Women´s Movement)"}] },
{ id: "IRL", name: "Ireland", info: [{name: "", work:"to be updated"}] },
{ id: "IRN", name: "Iran", info: [{name: "", work:"to be updated"}] },
{ id: "IRQ", name: "Iraq", info: [{name: "", work:"to be updated"}] },
{ id: "ISL", name: "Iceland", info: [{name: "", work:"to be updated"}] },
{ id: "ISR", name: "Israel", info: [{name: "", work:"to be updated"}] },
{ id: "ITA", name: "Italy", info: [{name: "", work:"to be updated"}] },
{ id: "JAM", name: "Jamaica", info: [{name: "", work:"to be updated"}] },
{ id: "JOR", name: "Jordan", info: [{name: "", work:"to be updated"}] },
{ id: "JPN", name: "Japan", info: [{name: "", work:"to be updated"}] },
{ id: "KAZ", name: "Kazakhstan", info: [{name: "", work:"to be updated"}] },
{ id: "KEN", name: "Kenya", info: [{name: "Nanjira Sambuli", work:"Nanjira Sambuli is a firm believer in empowerment and democratization through access to the digital world. "}] },
{ id: "KGZ", name: "Kyrgyzstan", info: [{name: "", work:"to be updated"}] },
{ id: "KHM", name: "Cambodia", info: [{name: "", work:"to be updated"}] },
{ id: "KOR", name: "South Korea", info: [{name: "", work:"to be updated"}] },
{ id: "OSA", name: "Kosovo", info: [{name: "", work:"to be updated"}] },
{ id: "KWT", name: "Kuwait", info: [{name: "", work:"to be updated"}] },
{ id: "LAO", name: "Laos", info: [{name: "", work:"to be updated"}] },
{ id: "LBN", name: "Lebanon", info: [{name: "", work:"to be updated"}] },
{ id: "LBR", name: "Liberia", info: [{name: "", work:"to be updated"}] },
{ id: "LBY", name: "Libya", info: [{name: "", work:"to be updated"}] },
{ id: "LKA", name: "Sri Lanka", info: [{name: "", work:"to be updated"}] },
{ id: "LSO", name: "Lesotho", info: [{name: "", work:"to be updated"}] },
{ id: "LTU", name: "Lithuania", info: [{name: "", work:"to be updated"}] },
{ id: "LUX", name: "Luxembourg", info: [{name: "", work:"to be updated"}] },
{ id: "LVA", name: "Latvia", info: [{name: "", work:"to be updated"}] },
{ id: "MAR", name: "Morocco", info: [{name: "", work:"to be updated"}] },
{ id: "MDA", name: "Moldova", info: [{name: "", work:"to be updated"}] },
{ id: "MDG", name: "Madagascar", info: [{name: "", work:"to be updated"}] },
{ id: "MEX", name: "Mexico", info: [{name: "", work:"to be updated"}] },
{ id: "MKD", name: "Macedonia", info: [{name: "", work:"to be updated"}] },
{ id: "MLI", name: "Mali", info: [{name: "", work:"to be updated"}] },
{ id: "MMR", name: "Myanmar", info: [{name: "", work:"to be updated"}] },
{ id: "MNE", name: "Montenegro", info: [{name: "", work:"to be updated"}] },
{ id: "MNG", name: "Mongolia", info: [{name: "", work:"to be updated"}] },
{ id: "MOZ", name: "Mozambique", info: [{name: "", work:"to be updated"}] },
{ id: "MRT", name: "Mauritania", info: [{name: "", work:"to be updated"}] },
{ id: "MWI", name: "Malawi", info: [{name: "", work:"to be updated"}] },
{ id: "MYS", name: "Malaysia", info: [{name: "", work:"to be updated"}] },
{ id: "NAM", name: "Namibia", info: [{name: "", work:"to be updated"}] },
{ id: "NCL", name: "New Caledonia", info: [{name: "", work:"to be updated"}] },
{ id: "NER", name: "Niger", info: [{name: "", work:"to be updated"}] },
{ id: "NGA", name: "Nigeria", info: [{name: "Sa'a Ibrahim", work:"Sa'a Ibrahim is a keen advocate of education for women."}] },
{ id: "NIC", name: "Nicaragua", info: [{name: "Ludwing Moncada", work:"Ludwing Moncada is a political activist from Ocotal, Nueva Segovia, in northern Nicaragua. Moncada co-founded Hora Cero, digital media for political advocacy. "}] },
{ id: "NLD", name: "Netherlands", info: [{name: "", work:"to be updated"}] },
{ id: "NOR", name: "Norway", info: [{name: "", work:"to be updated"}] },
{ id: "NPL", name: "Nepal", info: [{name: "Youth For Blood", work:"Youth For Blood is working to solve the nation's problem of blood scarcity. They support patients to find fresh blood, award people for donating blood, and advocate to pressure the authorities for quality blood transfusion services and policies."}] },
{ id: "NZL", name: "New Zealand", info: [{name: "", work:"to be updated"}] },
{ id: "OMN", name: "Oman", info: [{name: "", work:"to be updated"}] },
{ id: "PAK", name: "Pakistan", info: [{name: "Malala Yousafzai", work:" Malala Yousafzai has been an activist for female education."}] },
{ id: "PAN", name: "Panama", info: [{name: "", work:"to be updated"}] },
{ id: "PER", name: "Peru", info: [{name: "", work:"to be updated"}] },
{ id: "PHL", name: "Philippines", info: [{name: "ANAKBAYAN", work:"ANAKBAYAN is a comprehensive mass organization of the Filipino youth, turning to combine both organizing students and community youth."}] },
{ id: "PNG", name: "Papua New Guinea", info: [{name: "", work:"to be updated"}] },
{ id: "POL", name: "Poland", info: [{name: "", work:"to be updated"}] },
{ id: "PRI", name: "Puerto Rico", info: [{name: "", work:"to be updated"}] },
{ id: "PRK", name: "North Korea", info: [{name: "", work:"to be updated"}] },
{ id: "PRT", name: "Portugal", info: [{name: "", work:"to be updated"}] },
{ id: "PRY", name: "Paraguay", info: [{name: "", work:"to be updated"}] },
{ id: "QAT", name: "Qatar", info: [{name: "", work:"to be updated"}] },
{ id: "ROU", name: "Romania", info: [{name: "", work:"to be updated"}] },
{ id: "RUS", name: "Russia", info: [{name: "", work:"to be updated"}] },
{ id: "RWA", name: "Rwanda", info: [{name: "", work:"to be updated"}] },
{ id: "ESH", name: "Western Sahara", info: [{name: "", work:"to be updated"}] },
{ id: "SAU", name: "Saudi Arabia", info: [{name: "", work:"to be updated"}] },
{ id: "SDN", name: "Sudan", info: [{name: "Enass Muzamel", work:"Enass Muzamel is a humanitarian and development practitioner and civil society activist."}] },
{ id: "SDS", name: "South Sudan", info: [{name: "", work:"to be updated"}] },
{ id: "SEN", name: "Senegal", info: [{name: "", work:"to be updated"}] },
{ id: "SLB", name: "Solomon Islands", info: [{name: "", work:"to be updated"}] },
{ id: "SLE", name: "Sierra Leone", info: [{name: "", work:"to be updated"}] },
{ id: "SLV", name: "El Salvador", info: [{name: "", work:"to be updated"}] },
{ id: "ABV", name: "Somaliland", info: [{name: "", work:"to be updated"}] },
{ id: "SOM", name: "Somalia", info: [{name: "", work:"to be updated"}] },
{ id: "SRB", name: "Republic of Serbia", info: [{name: "", work:"to be updated"}] },
{ id: "SUR", name: "Suriname", info: [{name: "", work:"to be updated"}] },
{ id: "SVK", name: "Slovakia", info: [{name: "", work:"to be updated"}] },
{ id: "SVN", name: "Slovenia", info: [{name: "", work:"to be updated"}] },
{ id: "SWE", name: "Sweden", info: [{name: "", work:"to be updated"}] },
{ id: "SWZ", name: "Swaziland", info: [{name: "", work:"to be updated"}] },
{ id: "SYR", name: "Syria", info: [{name: "", work:"to be updated"}] },
{ id: "TCD", name: "Chad", info: [{name: "", work:"to be updated"}] },
{ id: "TGO", name: "Togo", info: [{name: "", work:"to be updated"}] },
{ id: "THA", name: "Thailand", info: [{name: "", work:"to be updated"}] },
{ id: "TJK", name: "Tajikistan", info: [{name: "", work:"to be updated"}] },
{ id: "TKM", name: "Turkmenistan", info: [{name: "", work:"to be updated"}] },
{ id: "TLS", name: "East Timor", info: [{name: "", work:"to be updated"}] },
{ id: "TTO", name: "Trinidad and Tobago", info: [{name: "", work:"to be updated"}] },
{ id: "TUN", name: "Tunisia", info: [{name: "", work:"to be updated"}] },
{ id: "TUR", name: "Turkey", info: [{name: "", work:"to be updated"}] },
{ id: "TWN", name: "Taiwan", info: [{name: "", work:"to be updated"}] },
{ id: "TZA", name: "United Republic of Tanzania", info: [{name: "", work:"to be updated"}] },
{ id: "UGA", name: "Uganda", info: [{name: "", work:"to be updated"}] },
{ id: "UKR", name: "Ukraine", info: [{name: "", work:"to be updated"}] },
{ id: "URY", name: "Uruguay", info: [{name: "", work:"to be updated"}] },
{ id: "USA", name: "USA", info: [{name: "Jazz Jennings", work:"Jazz Jennings and her family founded the Transkids Purple Rainbow Foundation, whose mission includes financial resources for homeless transyouth in need, education, and advocacy.."}] },
{ id: "UZB", name: "Uzbekistan", info: [{name: "", work:"to be updated"}] },
{ id: "VEN", name: "Venezuela", info: [{name: "", work:"to be updated"}] },
{ id: "VNM", name: "Vietnam", info: [{name: "", work:"to be updated"}] },
{ id: "VUT", name: "Vanuatu", info: [{name: "", work:"to be updated"}] },
{ id: "PSE", name: "West Bank", info: [{name: "", work:"to be updated"}] },
{ id: "YEM", name: "Yemen", info: [{name: "Radhya Almutawakel", work:"Radhya Almutawakel is a human rights defender and cofounder and chairperson of Mwatana, an independent Yemeni human rights organization that undertakes field investigations into human rights violations in Yemen and provides legal support to victims. "}] },
{ id: "ZAF", name: "South Africa", info: [{name: "Tsetse Tleane", work:"Technical advisor from Gesellschaft fur Internationale Zusammenarbeit (GIZ), using digital media to empower young people to create safer communities."}] },
{ id: "ZMB", name: "Zambia", info: [{name: "", work:"to be updated"}] },
{ id: "ZWE", name: "Zimbabwe", info: [{name: "", work:"to be updated"}] }]

